apiVersion: apps/v1
kind: Deployment
metadata:
  name: platforms-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platformapi
  template:
    metadata:
      labels:
        app: platformapi
    spec:
      containers:
        - name: platformapi
          image: betulalbayrak1999/platformapi:latest
---
---
apiVersion: v1
kind: Service
metadata:
  name: platforms-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: platformapi
  ports:
  - name: platformapi
    protocol: TCP
    port: 80
    targetPort: 80
 - name: plafromgrpc
    protocol: TCP
    port: 666
    targetPort: 666